baseURL = "https://liudon.xyz"
languageCode = "en-us"
title = "流动"
theme = "yinyang"
DefaultContentLanguage = "cn"
enableRobotsTXT = true
canonifyURLs = true

[author]
  name = "Liudon"
  homepage = "https://liudon.xyz/"

[languages]
  [languages.cn]
    contentDir = "content/zh"
    languageName = "Chinese"
    weight = 1

[params]
#disqus = "joway" # disqus account name
extraHead = '<style>article { max-width: 1180px; }</style>'
#mainSections = ["posts"]
lazyImage = true
description = ""
staticPrefix = "https://cdn.jsdelivr.net/gh/Liudon/liudon.github.io"

[[params.socials]]
name = "RSS"
link = "/index.xml"

[[params.socials]]
name = "About"
link = "/about/me"
