baseURL = "https://liudon.com"
languageCode = "en-us"
title = "流动"
theme = "yinyang"
DefaultContentLanguage = "cn"
enableRobotsTXT = true
canonifyURLs = true

[author]
  name = "Liudon"
  homepage = "https://liudon.com/"

[languages]
  [languages.cn]
    contentDir = "content/zh"
    languageName = "Chinese"
    weight = 1

[params]
#disqus = "joway" # disqus account name
extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=G-G9ZDJQN9E2"></script><script>window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}gtag('js', new Date());gtag('config', 'G-G9ZDJQN9E2');</script><style>article { max-width: 1180px; }</style>'
#mainSections = ["posts"]
lazyImage = true
description = ""
#staticPrefix = "https://cdn.jsdelivr.net/gh/liudon/liudon.github.io@master"

[[params.socials]]
name = "RSS"
link = "/index.xml"

[[params.socials]]
name = "About"
link = "/about/me/"