baseURL = "https://liudon.com"
languageCode = "en-us"
title = "流动"
theme = "yinyang"
DefaultContentLanguage = "cn"
enableRobotsTXT = true
canonifyURLs = true
keywords="流动,博客,liudon,生活,技术"
description="生活就是一个流动的过程"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = "tango"
    tabWidth = 4

[author]
  name = "Liudon"
  homepage = "https://liudon.com/"

[languages]
  [languages.cn]
    contentDir = "content/zh"
    languageName = "Chinese"
    weight = 1

[params]
headTitle = "Liudon"
description = "生活就是一个流动的过程."
#disqus = "joway" # disqus account name
extraHead = "<script async src=\"https://www.googletagmanager.com/gtag/js?id=G-G9ZDJQN9E2\"></script><script>window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}gtag('js', new Date());gtag('config', 'G-G9ZDJQN9E2');</script><style>article { max-width: 1180px; }</style>"
#mainSections = ["posts"]
lazyImage = true
staticPrefix = "https://cdn.jsdelivr.net/gh/liudon/liudon.github.io@master"

[[params.socials]]
name = "RSS"
link = "/index.xml"

[[params.socials]]
name = "About"
link = "/about/me/"