[build]
  publish = "public"
  # command = "npm run build && npm run ipfs-deploy"
  command = "sed 's/liudon.com/liudon.xyz/g' config.toml > config.toml && npm run build && npm run ipfs-deploy"

[context.production.environment]
  HUGO_VERSION = "0.98.0"
  NODE_VERSION = "18.10.0"
  NPM_VERSION = "8.19.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "https://liudon.netlify.com/*"
  to = "https://liudon.xyz/:splat"
  force = true
