name: Publish GitHub Pages

# Controls when the action will run.
on:
  workflow_dispatch:
    secrets:
      TOKEN:
        required: true
  workflow_call:
    secrets:
      TOKEN:
        required: true

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          # if your default branches is not master, please change it here
          ref: code

      - name: Checkout submodules
        run: git submodule update --init --recursive --remote

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: |
          ls -l ./
          hugo --gc --minify --cleanDestinationDir

      - name: Push
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_branch: master
          force_orphan: true
          publish_dir: ./public
          cname: liudon.com